// This file is generated by Prismic local builder. Update with care!

export { default as BannerSlice } from './BannerSlice'
export { default as FeaturedImage } from './FeaturedImage'
export { default as FullWidthImage } from './FullWidthImage'
export { default as ImageGallery } from './ImageGallery'
export { default as MegaMenu } from './MegaMenu'
export { default as QuoteSlice } from './QuoteSlice'
export { default as TextSlice } from './TextSlice'
